### ISSUE TITLE
Error: 'tabs' is not in list

### ISSUE THREAD

**Issue by romildo** [digitalxero/django-nav#3]
I wrote a simple application to test the django-nav package, but it does not work. django version is 1.4. I am getting the error:

ValueError at /

'tabs' is not in list

Request Method:     GET
Request URL:    http://127.0.0.1:8000/
Django Version:     1.4
Exception Type:     ValueError
Exception Value:    

'tabs' is not in list

Exception Location:     /usr/lib64/python2.7/site-packages/django_nav/templatetags/nav.py in get_nav, line 123
Python Executable:  /usr/bin/python2.7
Python Version:     2.7.3
Python Path:    

['/var/tmp/djnavtest',
 '/usr/lib64/python27.zip',
 '/usr/lib64/python2.7',
 '/usr/lib64/python2.7/plat-linux2',
 '/usr/lib64/python2.7/lib-tk',
 '/usr/lib64/python2.7/lib-old',
 '/usr/lib64/python2.7/lib-dynload',
 '/usr/lib64/python2.7/site-packages',
 '/usr/lib64/python2.7/site-packages/PIL',
 '/usr/lib64/python2.7/site-packages/gst-0.10',
 '/usr/lib64/python2.7/site-packages/gtk-2.0',
 '/usr/lib64/python2.7/site-packages/wx-2.8-gtk2-unicode',
 '/usr/lib64/portage/pym']

Server time:    Tue, 24 Jul 2012 06:16:48 -0500

[...]

/usr/lib64/python2.7/site-packages/django_nav/templatetags/nav.py in get_nav

```
    args['args'], args['kwargs'] = args_parser(' '.join(bits[bits.index(args['var_name'])+1:]))
```

**Comment by rickeyski** [comment]
Is your test application on github? If not could you post more information on your config. Thanks

**Comment by romildo** [comment]
I have put the application on bitbucket: https://bitbucket.org/romildo/djnavtest

**Comment by rickeyvisinski-kanban** [comment]
You didn't define user or user_anon nav groups. You only have main. You will need to create nav groups for those options in order to call them.

**Comment by romildo** [comment]
Even after defining user and user_anon nav groups the error persist.

Maybe it is a good idea to add a demo project in your package so that one can see exactly how to use it.

**Comment by rickeyvisinski-kanban** [comment]
Generally in django projects, views are required to render templates as well as defining nav.
